### ISSUE TITLE
crashed when lock to landscape mode

### ISSUE THREAD

**Issue by zzyyzz1992** [n4kz/react-native-material-dropdown#20]
when using react-orientation, app crashes when I lock to landscape mode.

Terminating app due to uncaught exception 'UIApplicationInvalidInterfaceOrientation', reason: 'Supported orientations has no common orientation with the application, and [RCTModalHostViewController shouldAutorotate] is returning YES'

similar issue:
xgfe/react-native-datepicker#28

**Comment by zzyyzz1992** [comment]
I've tested in my device, please approve [this](https://github.com/n4kz/react-native-material-dropdown/pull/21). :)

**Comment by n4kz** [comment]
Sorry for delayed reply and thanks for issue and PR. Looks like this was an RN bug and in was fixed in [`0.49.1`](https://github.com/facebook/react-native/commit/2444c54654807eb5a42d0cf67fe86a69fbb5a8a1). I will update this component in near future to `0.49.1` and will reopen this issue if anything goes wrong with orientation support.
