### ISSUE TITLE
How to reset dropdown?

### ISSUE THREAD

**Issue by PasinduDineth** [n4kz/react-native-material-dropdown#68]
Hi.. I am using dynamic data inside this drop down. So how to reset the drop down when a button click event triggered?
I tried to empty the data object i pass, but it won't change the  previously Selected value of the drop down.
Please help. Thank you!

**Comment by dlucidone** [comment]
@n4kz How can i achieve same

**Comment by dracostheblack** [comment]
Would like to know the same

**Comment by n4kz** [comment]
Thanks for question. For this moment re-rendering and updated can be tricky due to `PureComponents` used for performance reasons. Please take a look at #27 for more details.

As general solution I can suggest passing an extra prop to `Dropdown` and updating it when component should be re-rendered. I'm planning massive refactoring for next major release and will fix this behaviour.

**Comment by sankar2389** [comment]
Has the massive refactoring been done?
